# Generated by Django 3.1.2 on 2021-09-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='logo',
            field=models.ImageField(blank=True, upload_to='D:\x0corm\\media'),
        ),
    ]
